[package]
name = "encrusted_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.10.1"
rand = "0.4.2"
clap = "4.6.4"
regex = "1.1.0"
lazy_static = "1.2.0"
encrusted-heart = { path = "./encrusted-heart" }
itertools = "0.15.0"

[[bin]]
path = "src/main.rs"
name = "exiled"
bench = false
