name: tests
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests OTP:${{matrix.otp}} Elixir:${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['27.3.4']
        elixir: ['1.15.8', '1.18.4', '1.20.4']
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
